// thanks to Tim Fargiano for aggregating tolk_name suffixes, and for design

var tolk_names = 
[
    'albert',
    'algar',
    'algrim',
    'amanta',
    'anel',
    'elard',
    'egnor',
    'andir',
    'in',
    'athor',
    'an',
    'atar',
    'amir',
    'arion',
    'andil',
    'aranth',
    'arië',
    'ach',
    'ardil',
    'elimir',
    'ael',
    'akhôr',
    'ilzôr',
    'ador',
    'aglas',
    'agorn',
    'agorn',
    'agorn',
    'agorn',
    'agorn',
    'agorn',
    'agorn',
    'agorn',
    'agorn',
    'agorn',
    'agorn',
    'agorn',
    'agorn',
    'agorn',
    'agorn',
    'agorn',
    'agorn',
    'agorn',
    'agorn',
    'agorn',
    'agorn',
    'agorn',
    'agorn',
    'agorn',
    'agorn',
    'agost',
    'ahad',
    'ahael',
    'anarth',
    'antar',
    'anuir',
    'anwë',
    'aphant',
    'aphor',
    'assuil',
    'atan',
    'athorn',
    'athorn',
    'aval',
    'avir',
    'avorn',
    'edhel',
    'ien',
    'anatar',
    'anatar',
    'ulë',
    'antur',
    'aghâl',
    'og',
    'albo',
    'in',
    'agund',
    'ahir',
    'ahir',
    'ahir',
    'aran',
    'anor',
    'anor',
    'ecthor',
    'ecthor',
    'eg',
    'eg',
    'alion',
    'egor',
    'egorn',
    'egorn',
    'egorn',
    'egorn',
    'egorn',
    'egorn',
    'egorn',
    'egorn',
    'egund',
    'emir',
    'eth',
    'eorn',
    'eorn',
    'ereg',
    'egar',
    'egond',
    'egond',
    'elach',
    'il',
    'ilac',
    'omir',
    'omir',
    'omir',
    'alad',
    'ego',
    'olas',
    'olas',
    'olas',
    'olas',
    'olas',
    'olas',
    'olas',
    'olas',
    'olas',
    'olas',
    'olas',
    'olas',
    'olas',
    'olas',
    'olas',
    'olas',
    'olas',
    'olas',
    'olas',
    'olas',,
    'immacil',
    'anthir',
    'amir',
    'andine',
    'eborn',
    'eborn',
    'ebrían',
    'egorm',
    'epharn',
    'endur',
    'endur',
    'eorl',
    'irion',
    'iryon',
    'iryon',
    'ufin',
    'eron',
    'ethor',
    'ethor',
    'ethor',
    'ethor',
    'ethor',
    'ethor',
    'ethor',
    'ethor',
    'ethor',
    'ethor',
    'ethor',
    'ethor',
    'ethor',
    'ethor',
    'ethor',
    'ufin',
    'odas',
    'ior',
    'uchíl',
    'ior',
    'eric',
    'inas',
    'amira',
    'ilin',
    'ilin',
    'inhir',
    'alin',
    'almoth',
    'almoth',
    'antine',
    'inel',
    'anor',
    'atan',
    'oron',
    'acar',
    'acar',
    'arion',
    'arion',
    'athorn',
    'akil',
    'endil',
    'endur',
    'endur',
    'enwë',
    'edhel',
    'uréd',
    'urín',
    'eldir',
    'elyë',
    'ofor',
    'omer',
    'omund',
    'othain',
    'adan',
    'ellont',
    'endis',
    'estor',
    'iol',
    'estë',
    'erard',
    'endil',
    'endil',
    'endur',
    'endur',
    'endur',
    'athar',
    'amir',
    'amir',
    'amir',
    'anor',
    'umbras',
    'umbras',
    'ibert',
    'arfin',
    'iant',
    'agund',
    'inwë',
    'odacil',
    'inbras',
    'inbras',
    'am',
    'aláf',
    'awine',
    'erin',
    'uinur',
    'undin',
    'adhon',
    'ador',
    'adriel',
    'athil',
    'il',
    'elmir',
    'elmir',
    'ion',
    'aurung',
    'ingal',
    'imbold',
    'ilin',
    'uthláf',
    'indor',
    'ador',
    'aldad',
    'aldan',
    'aldar',
    'aldir',
    'aldir',
    'almir',
    'eden',
    'erhand',
    'orrenda',
    'ibald',
    'ion',
    'ugar',
    'ulcamo',
    'umor',
    'igrim',
    'iril',
    'irwen',
    'orsa',
    'undad',
    'undar',
    'unleth',
    'unthor',
    'uor',
    'ebrindal',
    'imin',
    'inyë',
    'indis',
    'indor',
    'ingil',
    'ingold',
    'ingwë',
    'oreth',
    'imë',
    'embard',
    'embold',
    'engrim',
    'engrim',
    'ildur',
    'ilmë',
    'ilmo',
    'umbras',
    'umbras',
    'orwen',
    'iniel',
    'aith',
    'urelin',
    'urinquë',
    'ender',
    'olas',
    'olas',
    'olas',
    'olas',
    'olas',
    'olas',
    'olas',
    'egolas',
    'enwë',
    'ugdush',
    'adoc',
    'aedhros',
    'aeglin',
    'aglor',
    'ach',
    'adan',
    'antur',
    'ach',
    'onwë',
    'iren',
    'igold',
    'auhúr',
    'eth',
    'ian',
    'egilda',
    'eldil',
    'eldor',
    'alcar',
    'ardil',
    'astan',
    'ohtar',
    'erindë',
    'orgoth',
    'edhwen',
    'uzgash',
    'aimi',
    'anië',
    'enor',
    'ondil',
    'ovacar',
    'odreth',
    'odreth',
    'odreth',
    'ofarnë',
    'omë',
    'omendil',
    'ophin',
    'ossë',
    'oher',
    'oher',
    'endur',
    'ula',
    'agast',
    'inard',
    'endacil',
    'endacil',
    'owan',
    'ufus',
    'adoc',
    'algant',
    'almar',
    'ira',
    'adas',
    'adoc',
    'uman',
    'edic',
    'ismond',
    'iondil',
    'iondil',
    'agol',
    'aga',
    'alcarin',
    'aldarion',
    'amandil',
    'ardamin',
    'endil',
    'antir',
    'imeldë',
    'andil',
    'annon',
    'astur',
    'ondor',
    'ondor',
    'ostar',
    'emnar',
    'erion',
    'ion',
    'or',
    'ambar',
    'ambar',
    'ambar',
    'entári',
    'antur',
    'ondil',
    'onwë',
    'anwion',
    'alda',
    'ibald',
    'imar',
    'entári'
];

// names gotten from U.S. census data

var english_names = 
{
    'Michael': true,
    'James': true,
    'David': true,
    'John': true,
    'Robert': true,
    'Christopher': true,
    'William': true,
    'Brian': true,
    'Mark': true,
    'Richard': true,
    'Jeffrey': true,
    'Scott': true,
    'Jason': true,
    'Kevin': true,
    'Steven': true,
    'Joseph': true,
    'Thomas': true,
    'Eric': true,
    'Daniel': true,
    'Timothy': true,
    'Charles': true,
    'Anthony': true,
    'Paul': true,
    'Matthew': true,
    'Kenneth': true,
    'Gregory': true,
    'Stephen': true,
    'Todd': true,
    'Ronald': true,
    'Donald': true,
    'Edward': true,
    'Andrew': true,
    'Patrick': true,
    'Shawn': true,
    'Gary': true,
    'Douglas': true,
    'Sean': true,
    'Keith': true,
    'Craig': true,
    'George': true,
    'Troy': true,
    'Jonathan': true,
    'Larry': true,
    'Peter': true,
    'Jerry': true,
    'Dennis': true,
    'Bradley': true,
    'Frank': true,
    'Raymond': true,
    'Jeffery': true,
    'Chad': true,
    'Aaron': true,
    'Bryan': true,
    'Terry': true,
    'Rodney': true,
    'Jose': true,
    'Tony': true,
    'Russell': true,
    'Randy': true,
    'Marc': true,
    'Roger': true,
    'Samuel': true,
    'Chris': true,
    'Shane': true,
    'Johnny': true,
    'Gerald': true,
    'Carl': true,
    'Jon': true,
    'Travis': true,
    'Jeremy': true,
    'Adam': true,
    'Marcus': true,
    'Phillip': true,
    'Brent': true,
    'Darren': true,
    'Lance': true,
    'Derek': true,
    'Billy': true,
    'Vincent': true,
    'Wayne': true,
    'Benjamin': true,
    'Joel': true,
    'Lawrence': true,
    'Corey': true,
    'Danny': true,
    'Jimmy': true,
    'Bobby': true,
    'Curtis': true,
    'Walter': true,
    'Joe': true,
    'Alan': true,
    'Philip': true,
    'Martin': true,
    'Bruce': true,
    'Juan': true,
    'Derrick': true,
    'Jay': true,
    'Carlos': true,
    'Brett': true,
    'Randall': true,
    'Erik': true,
    'Darrell': true,
    'Willie': true,
    'Henry': true,
    'Ricky': true,
    'Victor': true,
    'Albert': true,
    'Roy': true,
    'Glenn': true,
    'Dale': true,
    'Arthur': true,
    'Dean': true,
    'Allen': true,
    'Steve': true,
    'Frederick': true,
    'Jeff': true,
    'Barry': true,
    'Lee': true,
    'Jesse': true,
    'Kyle': true,
    'Antonio': true,
    'Harold': true,
    'Nicholas': true,
    'Louis': true,
    'Jamie': true,
    'Micheal': true,
    'Christian': true,
    'Jack': true,
    'Shannon': true,
    'Brandon': true,
    'Nathan': true,
    'Tyrone': true,
    'Ronnie': true,
    'Andre': true,
    'Kelly': true,
    'Alexander': true,
    'Mike': true,
    'Justin': true,
    'Ryan': true,
    'Brad': true,
    'Dwayne': true,
    'Ernest': true,
    'Reginald': true,
    'Leonard': true,
    'Luis': true,
    'Eugene': true,
    'Ralph': true,
    'Tommy': true,
    'Kurt': true,
    'Joshua': true,
    'Eddie': true,
    'Wesley': true,
    'Marvin': true,
    'Greg': true,
    'Glen': true,
    'Howard': true,
    'Stanley': true,
    'Kirk': true,
    'Mario': true,
    'Theodore': true,
    'Daryl': true,
    'Tracy': true,
    'Duane': true,
    'Cory': true,
    'Maurice': true,
    'Calvin': true,
    'Edwin': true,
    'Jerome': true,
    'Harry': true,
    'Manuel': true,
    'Melvin': true,
    'Ricardo': true,
    'Earl': true,
    'Damon': true,
    'Clinton': true,
    'Clifford': true,
    'Karl': true,
    'Neil': true,
    'Mitchell': true,
    'Darrin': true,
    'Norman': true,
    'Warren': true,
    'Fred': true,
    'Jody': true,
    'Jesus': true,
    'Terrence': true,
    'Ray': true,
    'Darin': true,
    'Wade': true,
    'Alfred': true,
    'Alex': true,
    'Francis': true,
    'Clarence': true,
    'Lonnie': true,
    'Darryl': true,
    'Roberto': true,
    'Miguel': true,
    'Tim': true,
    'Ruben': true,
    'Adrian': true,
    'Geoffrey': true,
    'Dustin': true,
    'Don': true,
    'Jim': true,
    'Gabriel': true,
    'Byron': true,
    'Leon': true,
    'Franklin': true,
    'Francisco': true,
    'Bernard': true,
    'Rick': true,
    'Stacy': true,
    'Terrance': true,
    'Gilbert': true,
    'Leroy': true,
    'Kent': true,
    'Joey': true,
    'Nathaniel': true,
    'Tom': true,
    'Hector': true,
    'Jorge': true,
    'Ian': true,
    'Vernon': true,
    'Alvin': true,
    'Oscar': true,
    'Roderick': true,
    'Dana': true,
    'Raul': true,
    'Angel': true,
    'Herbert': true,
    'Dwight': true,
    'Dan': true,
    'Bill': true,
    'Leslie': true,
    'Lewis': true,
    'Jessica': true,
    'Ashley': true,
    'Brittany': true,
    'Amanda': true,
    'Samantha': true,
    'Sarah': true,
    'Stephanie': true,
    'Jennifer': true,
    'Elizabeth': true,
    'Lauren': true,
    'Megan': true,
    'Emily': true,
    'Nicole': true,
    'Kayla': true,
    'Amber': true,
    'Rachel': true,
    'Courtney': true,
    'Danielle': true,
    'Heather': true,
    'Melissa': true,
    'Rebecca': true,
    'Michelle': true,
    'Tiffany': true,
    'Chelsea': true,
    'Christina': true,
    'Katherine': true,
    'Alyssa': true,
    'Jasmine': true,
    'Laura': true,
    'Hannah': true,
    'Kimberly': true,
    'Kelsey': true,
    'Victoria': true,
    'Sara': true,
    'Mary': true,
    'Erica': true,
    'Alexandra': true,
    'Amy': true,
    'Crystal': true,
    'Andrea': true,
    'Kristen': true,
    'Erin': true,
    'Brittney': true,
    'Anna': true,
    'Taylor': true,
    'Maria': true,
    'Allison': true,
    'Cassandra': true,
    'Caitlin': true,
    'Lindsey': true,
    'Angela': true,
    'Katie': true,
    'Alicia': true,
    'Vanessa': true,
    'Kathryn': true,
    'Morgan': true,
    'Jordan': true,
    'Whitney': true,
    'Brianna': true,
    'Christine': true,
    'Natalie': true,
    'Lisa': true,
    'Kristin': true,
    'Alexis': true,
    'Jacqueline': true,
    'Lindsay': true,
    'Brooke': true,
    'Catherine': true,
    'Olivia': true,
    'Erika': true,
    'Katelyn': true,
    'Monica': true,
    'Kristina': true,
    'Kaitlyn': true,
    'Paige': true,
    'Molly': true,
    'Jenna': true,
    'Leah': true,
    'Julia': true,
    'Bianca': true,
    'Tara': true,
    'Melanie': true,
    'Marissa': true,
    'Cynthia': true,
    'Holly': true,
    'Abigail': true,
    'Meghan': true,
    'Kathleen': true,
    'Julie': true,
    'Ariel': true,
    'Alexandria': true,
    'Veronica': true,
    'Patricia': true,
    'Diana': true,
    'Gabrielle': true,
    'Shelby': true,
    'Kaitlin': true,
    'Margaret': true,
    'Brandi': true,
    'Krystal': true,
    'Natasha': true,
    'Casey': true,
    'Bethany': true,
    'Haley': true,
    'Briana': true,
    'Kara': true,
    'Rachael': true,
    'Miranda': true,
    'Breanna': true,
    'Caroline': true,
    'Kendra': true,
    'Sabrina': true,
    'Angelica': true,
    'Karen': true,
    'Felicia': true,
    'Jillian': true,
    'Brenda': true,
    'Ana': true,
    'Desiree': true,
    'Meagan': true,
    'Katrina': true,
    'Chelsey': true,
    'Valerie': true,
    'Emma': true,
    'Nancy': true,
    'Alison': true,
    'Monique': true,
    'Sandra': true,
    'Alisha': true,
    'Britney': true,
    'Brandy': true,
    'Joanna': true,
    'Gina': true,
    'Grace': true,
    'Sierra': true,
    'Candace': true,
    'Jaclyn': true,
    'Adriana': true,
    'Krista': true,
    'Alexa': true,
    'Candice': true,
    'Lacey': true,
    'Rebekah': true,
    'Sydney': true,
    'Nichole': true,
    'Denise': true,
    'Dominique': true,
    'Ashlee': true,
    'Anne': true,
    'Yesenia': true,
    'Kirsten': true,
    'Deanna': true,
    'Claire': true,
    'Colleen': true,
    'Audrey': true,
    'Mallory': true,
    'Carly': true,
    'Tabitha': true,
    'Cristina': true,
    'Raven': true,
    'Priscilla': true,
    'Stacey': true,
    'Carolyn': true,
    'Carrie': true,
    'Kiara': true,
    'Susan': true,
    'Linda': true,
    'Mercedes': true,
    'Autumn': true,
    'Ashleigh': true,
    'Kylie': true,
    'Teresa': true,
    'Gabriela': true,
    'Kelli': true,
    'Caitlyn': true,
    'Renee': true,
    'Arielle': true,
    'Cindy': true,
    'Ebony': true,
    'Justine': true,
    'Karina': true,
    'Meredith': true,
    'Bridget': true,
    'Hillary': true,
    'Daisy': true,
    'Amelia': true,
    'Mayra': true,
    'Theresa': true,
    'Claudia': true,
    'Madeline': true,
    'Sasha': true,
    'Heidi': true,
    'Robin': true,
    'Destiny': true,
    'Madison': true,
    'Lydia': true,
    'Savannah': true,
    'Wendy': true,
    'Barbara': true,
    'Melinda': true,
    'Tamara': true,
    'Ellen': true,
    'Alejandra': true,
    'Chloe': true,
    'Marie': true,
    'Jenny': true,
    'Virginia': true,
    'Kasey': true,
    'Jocelyn': true,
    'Carmen': true,
    'Jade': true,
    'Evelyn': true,
    'Jacquelyn': true,
    'Abby': true,
    'Janet': true,
    'Martha': true,
    'Cortney': true,
    'Bailey': true,
    'Ariana': true,
    'Cassie': true,
    'Brittani': true,
    'Jasmin': true,
    'Hilary': true,
    'Kaylee': true,
    'Cara': true,
    'Adrienne': true,
    'Allyson': true,
    'Kristine': true,
    'Pamela': true,
    'Raquel': true,
    'Tina': true,
    'Gloria': true,
    'Rosa': true,
    'Camille': true,
    'Michele': true,
    'Tiara': true,
    'Tasha': true,
    'Mackenzie': true,
    'Kristy': true,
    'Ann': true,
    'Shawna': true,
    'Sophia': true,
    'Tanya': true,
    'Jessie': true,
    'Latoya': true,
    'Marisa': true,
    'Kari': true,
    'Carissa': true,
    'Janelle': true,
    'Mariah': true,
    'Nina': true,
    'Angelina': true,
    'Deborah': true,
    'Carla': true,
    'Kellie': true,
    'Elise': true,
    'Hope': true,
    'Hayley': true,
    'Cierra': true,
    'Kristi': true,
    'Kate': true,
    'Summer': true,
    'Aimee': true,
    'Chelsie': true,
    'Sharon': true,
    'Toni': true,
    'Karla': true,
    'Tammy': true,
    'Dawn': true,
    'Lori': true,
    'Donna': true,
    'Cheryl': true,
    'Rhonda': true,
    'Debra': true,
    'Tonya': true,
    'Jill': true,
    'Tracey': true,
    'Paula': true,
    'Sherry': true,
    'Diane': true,
    'Carol': true,
    'Sheila': true,
    'Kathy': true,
    'Kim': true,
    'Regina': true,
    'Suzanne': true,
    'Laurie': true,
    'Beth': true,
    'Jodi': true,
    'Traci': true,
    'Shelly': true,
    'Christy': true,
    'Yolanda': true,
    'Terri': true,
    'Connie': true,
    'Lynn': true,
    'Sherri': true,
    'Tricia': true,
    'Anita': true,
    'Annette': true,
    'Bonnie': true,
    'Sonya': true,
    'Wanda': true,
    'Vicki': true,
    'Cathy': true,
    'Sheri': true,
    'Yvonne': true,
    'Shelley': true,
    'Janice': true,
    'Tracie': true,
    'Debbie': true,
    'Beverly': true,
    'Darlene': true,
    'Penny': true,
    'Jean': true,
    'Becky': true,
    'Yvette': true,
    'Joyce': true,
    'Stacie': true,
    'Charlotte': true,
    'Charlene': true,
    'Betty': true,
    'Joanne': true,
    'Trina': true,
    'Peggy': true,
    'Tammie': true,
    'Kerry': true,
    'Judy': true,
    'Ruth': true,
    'Dorothy': true,
    'Kristie': true,
    'Maureen': true,
    'Rose': true,
    'Joy': true,
    'Kimberley': true,
    'Sonia': true,
    'Sylvia': true,
    'Jeanette': true,
    'Helen': true,
    'Judith': true,
    'Vickie': true,
    'Shirley': true,
    'Frances': true,
    'Alice': true,
    'Belinda': true,
    'Jane': true,
    'Rita': true,
    'Jeanne': true,
    'Joann': true,
    'Tami': true,
    'Dina': true,
    'Dena': true,
    'Robyn': true,
    'Kelley': true,
    'Leigh': true,
    'Sheryl': true,
    'Elaine': true,
    'Norma': true,
    'Tonia': true,
    'Gail': true,
    'Kerri': true,
    'Marsha': true,
    'Ginger': true,
    'Roberta': true,
    'Jackie': true,
    'Loretta': true,
    'Deana': true,
    'Ronda': true,
    'Lara': true,
    'Christie': true,
    'Sonja': true,
    'Joan': true,
    'Angie': true,
    'Marcia': true,
    'Eileen': true,
    'Juanita': true,
    'Marilyn': true,
    'Sally': true,
    'Gretchen': true,
    'Sandy': true,
    'Bobbie': true,
    'Gwendolyn': true,
    'Christa': true,
    'Lora': true,
    'Shari': true,
    'Shelia': true,
    'Cheri': true,
    'Rochelle': true,
    'Melody': true,
    'Lorraine': true,
    'Lynette': true,
    'Alisa': true,
    'Misty': true,
    'Staci': true,
    'Billie': true,
    'Marla': true,
    'Teri': true,
    'Irene': true,
    'Stefanie': true,
    'Jodie': true,
    'Karin': true,
    'Janine': true,
    'Candy': true,
    'Jana': true,
    'Eva': true,
    'Antoinette': true,
    'Roxanne': true,
    'Cherie': true,
    'Jacob': true,
    'Tyler': true,
    'Zachary': true,
    'Cody': true,
    'Austin': true,
    'Ethan': true,
    'Cameron': true,
    'Jared': true,
    'Evan': true,
    'Trevor': true,
    'Dylan': true,
    'Caleb': true,
    'Blake': true,
    'Devin': true,
    'Garrett': true,
    'Seth': true,
    'Logan': true,
    'Spencer': true,
    'Johnathan': true,
    'Chase': true,
    'Lucas': true,
    'Luke': true,
    'Colin': true,
    'Julian': true,
    'Jonathon': true,
    'Alejandro': true,
    'Isaac': true,
    'Colton': true,
    'Jake': true,
    'Edgar': true,
    'Mathew': true,
    'Eduardo': true,
    'Devon': true,
    'Darius': true,
    'Clayton': true,
    'Jeremiah': true,
    'Brendan': true,
    'Javier': true,
    'Omar': true,
    'Drew': true,
    'Sergio': true,
    'Kristopher': true,
    'Bryce': true,
    'Max': true,
    'Ivan': true,
    'Fernando': true,
    'Levi': true,
    'Grant': true,
    'Dillon': true,
    'Xavier': true,
    'Nicolas': true,
    'Dominic': true,
    'Maxwell': true,
    'Ross': true,
    'Dalton': true,
    'Julio': true,
    'Dakota': true,
    'Pedro': true,
    'Preston': true,
    'Cesar': true,
    'Rafael': true,
    'Andres': true,
    'Bryant': true,
    'Isaiah': true,
    'Mason': true,
    'Jaime': true,
    'Emmanuel': true,
    'Hunter': true,
    'Tanner': true,
    'Connor': true,
    'Erick': true,
    'Alberto': true,
    'Shaun': true,
    'Marco': true,
    'Noah': true,
    'Armando': true,
    'Zachery': true,
    'Micah': true,
    'Collin': true,
    'Malcolm': true,
    'Elijah': true,
    'Abraham': true,
    'Colby': true,
    'Jamal': true,
    'Cole': true,
    'Johnathon': true,
    'Ramon': true,
    'Trent': true,
    'Gerardo': true,
    'Brock': true,
    'Arturo': true,
    'Marquis': true,
    'Enrique': true,
    'Trenton': true,
    'Phyllis': true,
    'Doris': true,
    'Lois': true,
    'Constance': true,
    'Glenda': true,
    'Dianne': true,
    'Sue': true,
    'Rosemary': true,
    'Geraldine': true,
    'Annie': true,
    'Lynda': true,
    'Louise': true,
    'Marlene': true,
    'Patsy': true,
    'Marjorie': true,
    'Kay': true,
    'Delores': true,
    'Ruby': true,
    'Arlene': true,
    'Gayle': true,
    'Mildred': true,
    'Janis': true,
    'Vivian': true,
    'Dolores': true,
    'Carole': true,
    'Josephine': true,
    'Edith': true,
    'Paulette': true,
    'Georgia': true,
    'Lynne': true,
    'Lillian': true,
    'Edna': true,
    'Esther': true,
    'Pauline': true,
    'Janie': true,
    'Jan': true,
    'Wilma': true,
    'Ethel': true,
    'Clara': true,
    'Lucille': true,
    'Gladys': true,
    'Bonita': true,
    'Margie': true,
    'Thelma': true,
    'Dianna': true,
    'Florence': true,
    'Marianne': true,
    'Bertha': true,
    'Marion': true,
    'Ella': true,
    'Eleanor': true,
    'Maryann': true,
    'Lillie': true,
    'Lana': true,
    'Bernice': true,
    'Lucy': true,
    'Faye': true,
    'Beatrice': true,
    'Marian': true,
    'Maxine': true,
    'Vicky': true,
    'Ida': true,
    'Hazel': true,
    'Francine': true,
    'Nora': true,
    'Stella': true,
    'Vera': true,
    'Rosie': true,
    'Mona': true,
    'Alma': true,
    'Bernadette': true,
    'Ramona': true,
    'Myra': true,
    'Gordon': true,
    'Gene': true,
    'Lloyd': true,
    'Clyde': true,
    'Jimmie': true,
    'Allan': true,
    'Floyd': true,
    'Harvey': true,
    'Lester': true,
    'Donnie': true,
    'Charlie': true,
    'Freddie': true,
    'Johnnie': true,
    'Herman': true,
    'Leo': true,
    'Milton': true,
    'Randolph': true,
    'Garry': true,
    'Arnold': true,
    'Chester': true,
    'Ted': true,
    'Cecil': true,
    'Rickey': true,
    'Claude': true,
    'Guy': true,
    'Stuart': true,
    'Roland': true,
    'Fredrick': true,
    'Gerard': true,
    'Perry': true,
    'Marshall': true,
    'Sidney': true,
    'Rex': true,
    'Wallace': true,
    'Clifton': true,
    'Bob': true,
    'Hugh': true,
    'Sam': true,
    'Hailey': true,
    'Isabella': true,
    'Faith': true,
    'Makayla': true,
    'Trinity': true,
    'Zoe': true,
    'Jada': true,
    'Mia': true,
    'Isabel': true,
    'Gabriella': true,
    'Cheyenne': true,
    'Cassidy': true,
    'Mikayla': true,
    'Maya': true,
    'Lily': true,
    'Madelyn': true,
    'Arianna': true,
    'Riley': true,
    'Mckenzie': true,
    'Skylar': true,
    'Kennedy': true,
    'Isabelle': true,
    'Michaela': true,
    'Daniela': true,
    'Sophie': true,
    'Sofia': true,
    'Diamond': true,
    'Payton': true,
    'Alexia': true,
    'Peyton': true,
    'Hanna': true,
    'Mya': true,
    'Avery': true,
    'Brooklyn': true,
    'Ashlyn': true,
    'Ava': true,
    'Alondra': true,
    'Camryn': true,
    'Naomi': true,
    'Jordyn': true,
    'Mckenna': true,
    'Kendall': true,
    'Selena': true,
    'Esmeralda': true,
    'Amaya': true,
    'Kylee': true,
    'Maggie': true,
    'Makenzie': true,
    'Kyra': true,
    'Delaney': true,
    'Serena': true,
    'Savanna': true,
    'Aaliyah': true,
    'Giselle': true,
    'Adrianna': true,
    'Asia': true,
    'Natalia': true,
    'Valeria': true,
    'Aubrey': true,
    'Lauryn': true,
    'Jazmin': true,
    'Katelynn': true,
    'Macy': true,
    'Elena': true,
    'Kyla': true,
    'Jazmine': true,
    'Gianna': true,
    'Juliana': true,
    'Fatima': true,
    'Gracie': true,
    'Sadie': true,
    'Guadalupe': true,
    'Genesis': true,
    'Julianna': true,
    'Skyler': true,
    'Tatiana': true,
    'Alexus': true,
    'Alana': true,
    'Nadia': true,
    'Haylee': true,
    'Jayla': true,
    'Tori': true,
    'Tessa': true,
    'Carolina': true,
    'Jaqueline': true,
    'Celeste': true,
    'Kiana': true,
    'Makenna': true,
    'Alissa': true,
    'Madeleine': true,
    'Miriam': true,
    'Ciara': true,
    'Cecilia': true,
    'Kassandra': true,
    'Reagan': true,
    'Aliyah': true,
    'Rylee': true,
    'Shania': true,
    'Kira': true,
    'Hallie': true,
    'Liliana': true,
    'Imani': true,
    'Kailey': true,
    'Nia': true,
    'Anastasia': true,
    'Brenna': true,
    'Shayla': true,
    'Kassidy': true,
    'Alaina': true,
    'Jackson': true,
    'Sebastian': true,
    'Gavin': true,
    'Tristan': true,
    'Jalen': true,
    'Wyatt': true,
    'Aidan': true,
    'Carson': true,
    'Parker': true,
    'Hayden': true,
    'Liam': true,
    'Kaleb': true,
    'Owen': true,
    'Diego': true,
    'Carter': true,
    'Jaden': true,
    'Alec': true,
    'Cristian': true,
    'Gage': true,
    'Dawson': true,
    'Jakob': true,
    'Chandler': true,
    'Malik': true,
    'Josiah': true,
    'Nolan': true,
    'Harrison': true,
    'Brady': true,
    'Conner': true,
    'Jonah': true,
    'Jayden': true,
    'Brayden': true,
    'Landon': true,
    'Giovanni': true,
    'Braden': true,
    'Damian': true,
    'Donovan': true,
    'Andy': true,
    'Chance': true,
    'Trey': true,
    'Cade': true,
    'Jaylen': true,
    'Griffin': true,
    'Eli': true,
    'Kobe': true,
    'Caden': true,
    'Marcos': true,
    'Cooper': true,
    'Elias': true,
    'Brenden': true,
    'Israel': true,
    'Zane': true,
    'Dante': true,
    'Josue': true,
    'Zackary': true,
    'Leonardo': true,
    'Ashton': true,
    'Miles': true,
    'Damien': true,
    'Gustavo': true,
    'Drake': true,
    'Simon': true,
    'Kameron': true,
    'Bryson': true,
    'Dominick': true,
    'Kaden': true,
    'Brennan': true,
    'Nickolas': true,
    'Fabian': true,
    'Keegan': true,
    'Saul': true,
    'Tucker': true,
    'Myles': true,
    'Corbin': true,
    'Deandre': true,
    'Lane': true,
    'Pablo': true,
    'Jarrett': true,
    'Ron': true,
    'Nabby': true,
    'Abe': true,
    'Bert': true,
    'Alla': true,
    'Freddy': true,
    'Allie': true,
    'Elsie': true,
    'Manda': true,
    'Mandy': true,
    'Mel': true,
    'Millie': true,
    'Nan': true,
    'Nana': true,
    'Nanny': true,
    'Netta': true,
    'Arly': true,
    'Lena': true,
    'Art': true,
    'Bab': true,
    'Babs': true,
    'Barby': true,
    'Bea': true,
    'Trisha': true,
    'Trix': true,
    'Trixie': true,
    'Belle': true,
    'Ben': true,
    'Benjy': true,
    'Bennie': true,
    'Barney': true,
    'Berney': true,
    'Bernie': true,
    'Bertie': true,
    'Birdie': true,
    'Biddie': true,
    'Biddy': true,
    'Bridgie': true,
    'Bridie': true,
    'Cal': true,
    'Vin': true,
    'Vinny': true,
    'Cam': true,
    'Ronny': true,
    'Cammie': true,
    'K.C.': true,
    'Katy': true,
    'Kit': true,
    'Kittie': true,
    'Celia': true,
    'Cissy': true,
    'Chick': true,
    'Chuck': true,
    'Char': true,
    'Lotta': true,
    'Lottie': true,
    'Chet': true,
    'Crissy': true,
    'Kris': true,
    'Chrissy': true,
    'Clair': true,
    'Clare': true,
    'Cliff': true,
    'Ford': true,
    'Barack': true,
    'Curt': true,
    'Cintha': true,
    'Dahl': true,
    'Darry': true,
    'Dave': true,
    'Davey': true,
    'Deb': true,
    'Debby': true,
    'Dee': true,
    'Dell': true,
    'Della': true,
    'Lola': true,
    'Lolly': true,
    'Denny': true,
    'Dom': true,
    'Donny': true,
    'Dony': true,
    'Dolly': true,
    'Dortha': true,
    'Dot': true,
    'Dotty': true,
    'Eddy': true,
    'Edie': true,
    'Edye': true,
    'Ned': true,
    'Teddy': true,
    'Win': true,
    'Ellie': true,
    'Lanna': true,
    'Lenora': true,
    'Nelly': true,
    'Lias': true,
    'Lige': true,
    'Bess': true,
    'Bessie': true,
    'Betsy': true,
    'Eliza': true,
    'Lib': true,
    'Libby': true,
    'Liz': true,
    'Liza': true,
    'Lizzie': true,
    'Emmy': true,
    'Ernie': true,
    'Fay': true,
    'Flo': true,
    'Flora': true,
    'Flossy': true,
    'Fanny': true,
    'Fran': true,
    'Francie': true,
    'Frankie': true,
    'Frannie': true,
    'Franniey': true,
    'Sis': true,
    'Fritz': true,
    'Gabby': true,
    'Gabe': true,
    'Geoff': true,
    'Gerry': true,
    'Gerrie': true,
    'Gil': true,
    'Wilber': true,
    'Gwen': true,
    'Hal': true,
    'Hank': true,
    'Herb': true,
    'Rena': true,
    'Ike': true,
    'Zeke': true,
    'Bell': true,
    'Bella': true,
    'Issy': true,
    'Nib': true,
    'Nibby': true,
    'Tibbie': true,
    'Jaap': true,
    'Jem': true,
    'Jennie': true,
    'Jeannie': true,
    'Nettie': true,
    'Jereme': true,
    'Nonie': true,
    'Jock': true,
    'Jos': true,
    'Fina': true,
    'Josey': true,
    'Josh': true,
    'Nita': true,
    'Jule': true,
    'Kaye': true,
    'Ken': true,
    'Kenny': true,
    'Kendrick': true,
    'Lon': true,
    'Lonny': true,
    'Lorne': true,
    'Lorry': true,
    'Len': true,
    'Lenny': true,
    'Lineau': true,
    'Les': true,
    'Lil': true,
    'Lilly': true,
    'Lindy': true,
    'Etta': true,
    'Lorrie': true,
    'Retta': true,
    'Lou': true,
    'Cille': true,
    'Lyddy': true,
    'Maddy': true,
    'Madge': true,
    'Magda': true,
    'Gretta': true,
    'Maggy': true,
    'Marge': true,
    'Margery': true,
    'Margy': true,
    'Meg': true,
    'Midge': true,
    'Peg': true,
    'Marty': true,
    'Mat': true,
    'Mattie': true,
    'Patty': true,
    'Marv': true,
    'Mae': true,
    'Mamie': true,
    'Mitzi': true,
    'Polly': true,
    'Matt': true,
    'Matty': true,
    'Thias': true,
    'Thys': true,
    'Morey': true,
    'Mindy': true,
    'Lissa': true,
    'Milly': true,
    'Missy': true,
    'Mick': true,
    'Micky': true,
    'Mickey': true,
    'Mira': true,
    'Mimi': true,
    'Mitch': true,
    'Natty': true,
    'Nat': true,
    'Nate': true,
    'Than': true,
    'Claas': true,
    'Claes': true,
    'Nick': true,
    'Livia': true,
    'Nollie': true,
    'Ollie': true,
    'Pam': true,
    'Pat': true,
    'Paddy': true,
    'Pate': true,
    'Lina': true,
    'Pete': true,
    'Phil': true,
    'Cilla': true,
    'Prissy': true,
    'Dolph': true,
    'Becca': true,
    'Beck': true,
    'Reba': true,
    'Reggie': true,
    'Naldo': true,
    'Reg': true,
    'Renny': true,
    'Dick': true,
    'Dickie': true,
    'Dickon': true,
    'Dicky': true,
    'Rich': true,
    'Dob': true,
    'Dobbin': true,
    'Hob': true,
    'Hobkin': true,
    'Rob': true,
    'Robbie': true,
    'Hodge': true,
    'Robby': true,
    'Rod': true,
    'Roge': true,
    'Rupert': true,
    'Lanny': true,
    'Orlando': true,
    'Rollo': true,
    'Rolly': true,
    'Roxie': true,
    'Russ': true,
    'Rusty': true,
    'Brina': true,
    'Sammy': true,
    'Shirl': true,
    'Sid': true,
    'Syd': true,
    'Sion': true,
    'Steph': true,
    'Stu': true,
    'Sukey': true,
    'Susie': true,
    'Suzie': true,
    'Tabby': true,
    'Theo': true,
    'Tess': true,
    'Tessie': true,
    'Thirza': true,
    'Thursa': true,
    'Thom': true,
    'Timmy': true,
    'Val': true,
    'Essa': true,
    'Nessa': true,
    'Vanna': true,
    'Franky': true,
    'Frony': true,
    'Ronie': true,
    'Ronna': true,
    'Vonnie': true,
    'Vic': true,
    'Torie': true,
    'Tory': true,
    'Vince': true,
    'Vinnie': true,
    'Ginny': true,
    'Virgy': true,
    'Wally': true,
    'Walt': true,
    'Bela': true,
    'Will': true,
    'Willy': true,
    'Vonna': true,
    'Brody': true,
    'Eve': true
};

// tolk_dict keeps track of tolkien-ized names on page
var tolk_MAX = tolk_names.length;
var tolk_dict = {};

// syllable counting function taken from 
// https://stackoverflow.com/questions/5686483/how-to-compute-number-of-syllables-in-a-word-in-javascript
function syll_count(word) 
{
    word = word.toLowerCase();
    if(word.length <= 3) { return 1; }  
    
    word = word.replace(/(?:[^laeiouy]es|ed|[^laeiouy]e)$/, '');
    word = word.replace(/^y/, '');
    if (word.match(/[aeiouy]{1,2}/g) == null) { return 1; }
    return word.match(/[aeiouy]{1,2}/g).length;                    
}

// tolkien-ize name
function tolk_name(name_given) 
{
    while(syll_count(name_given) > 1) {
        name_given = name_given.substring(0, name_given.length - 1);
    }
    while(name_given.length > 2 && /[aeiou]/.test(name_given.charAt(name_given.length - 1))) {
        name_given = name_given.substring(0, name_given.length - 1);
    }
    var index = Math.floor(Math.random() * tolk_MAX);
    var choice = tolk_names[index];
    var name_tolkd = name_given.concat(choice);
    return name_tolkd;
}

// helper function to replace instance of name in text
function replace_instance(txt, name) 
{
    var regex = new RegExp("\\b"+name+"\\b");
    txt = txt.replace(regex, tolk_dict[name]);
    return txt;
}

// much of below functionality taken from "Millenials to Snake People" chrome extension
// source code at https://github.com/ericwbailey/millennials-to-snake-people
function walk(rootNode)
{
    // Find all the text nodes in rootNode
    var walker = document.createTreeWalker(
        rootNode,
        NodeFilter.SHOW_TEXT,
        null,
        false
    ),
    node;

    // Modify each text node's value
    while (node = walker.nextNode()) {
        handleText(node);
    }
}

function handleText(textNode) {
  textNode.nodeValue = replaceText(textNode.nodeValue);
}

// replace instances of name with tolkien-ized version
function replaceText(v)
{
    if (typeof(v) === 'undefined' || !v) { return v; }
    var text = String(v);
    
    // tokenize by special characters
    var text_parsed = text.split(/[`!@#();:'",.<>\{\}\[\]\\\/ ]/);
    var text_len = text_parsed.length;
    
    // reserved object properties that are techincally 'in' tolk_dict
    var dont_hash = ['toString', 'toLocaleString', 'valueOf', 'hasOwnProperty',
            'isPrototypeOf', 'propertyIsEnumerable', 'constructor'];
    
    for (var k = 0; k < text_len; k++) {
        
        // check that word is valid replaceable text
        var word = text_parsed[k];
        if (word in dont_hash) { continue; }
        if (typeof(word) === 'undefined' || !word) { continue; }
        
        // check if word has already been tolkien-ized; else if name, tolkien-ize it and update tolk_dict
        if (word in tolk_dict && typeof(tolk_dict[word]) !== 'undefined') {
            text = replace_instance(text, word);
        } else if (english_names[word]) {
            var name_new = tolk_name(word);
            tolk_dict[word] = name_new;
            text = replace_instance(text, word);
        }
    }
    return text;
}

// Returns true if a node should *not* be altered in any way
function isForbiddenNode(node) {
    return node.isContentEditable || // DraftJS and many others
    (node.parentNode && node.parentNode.isContentEditable) || // Special case for Gmail
    (node.tagName && (node.tagName.toLowerCase() == "textarea" || // Some catch-alls
                     node.tagName.toLowerCase() == "input"));
}

// The callback used for the document body and title observers
function observerCallback(mutations) {
    var i, node;

    mutations.forEach(function(mutation) {
        for (i = 0; i < mutation.addedNodes.length; i++) {
            node = mutation.addedNodes[i];
            if (isForbiddenNode(node)) {
                // Should never operate on user-editable content
                continue;
            } else if (node.nodeType === 3) {
                // Replace the text for text nodes
                handleText(node);
            } else {
                // Otherwise, find text nodes within the given node and replace text
                walk(node);
            }
        }
    });
}

// Walk the doc (document) body, replace the title, and observe the body and title
function walkAndObserve(doc) {
    var docTitle = doc.getElementsByTagName('title')[0],
    observerConfig = {
        characterData: true,
        childList: true,
        subtree: true
    },
    bodyObserver, titleObserver;

    // Do the initial text replacements in the document body and title
    walk(doc.body);
    doc.title = replaceText(doc.title);

    // Observe the body so that we replace text in any added/modified nodes
    bodyObserver = new MutationObserver(observerCallback);
    bodyObserver.observe(doc.body, observerConfig);

    // Observe the title so we can handle any modifications there
    if (docTitle) {
        titleObserver = new MutationObserver(observerCallback);
        titleObserver.observe(docTitle, observerConfig);
    }
}
walkAndObserve(document);